name: CI
on:
  push: { branches: [ master, main ] }
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Temurin 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven
      - name: Run tests
        run: mvn -q -B -Ptest test
        env:
          BASE_URL: https://reqres.in
      - name: Upload Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: |
            **/allure-results/**
            target/surefire-reports/**